# Generated by Django 3.2.13 on 2025-12-24 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20251219_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
